/*
 Navicat Premium Data Transfer

 Source Server         : SYSTEM
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Schema         : DJANGO_DB

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 02/11/2020 22:42:54
*/


-- ----------------------------
-- Table structure for POSTGRAD
-- ----------------------------
DROP TABLE "DJANGO_DB"."POSTGRAD";
CREATE TABLE "DJANGO_DB"."POSTGRAD" (
  "STD_ID" NUMBER(7,0) NOT NULL,
  "MSC" VARCHAR2(30 BYTE),
  "PHD" VARCHAR2(30 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of POSTGRAD
-- ----------------------------
INSERT INTO "DJANGO_DB"."POSTGRAD" VALUES ('1705004', NULL, NULL);
INSERT INTO "DJANGO_DB"."POSTGRAD" VALUES ('1705014', NULL, NULL);
INSERT INTO "DJANGO_DB"."POSTGRAD" VALUES ('1705098', NULL, NULL);
INSERT INTO "DJANGO_DB"."POSTGRAD" VALUES ('1705002', NULL, NULL);
INSERT INTO "DJANGO_DB"."POSTGRAD" VALUES ('1705008', NULL, NULL);
INSERT INTO "DJANGO_DB"."POSTGRAD" VALUES ('1705056', NULL, NULL);
INSERT INTO "DJANGO_DB"."POSTGRAD" VALUES ('1705015', NULL, NULL);
INSERT INTO "DJANGO_DB"."POSTGRAD" VALUES ('1705039', NULL, NULL);
