/*
 Navicat Premium Data Transfer

 Source Server         : PROJ
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Schema         : DJANGO_DB

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 18/11/2020 22:30:58
*/


-- ----------------------------
-- Table structure for JOB_POST
-- ----------------------------
DROP TABLE "DJANGO_DB"."JOB_POST";
CREATE TABLE "DJANGO_DB"."JOB_POST" (
  "POST_ID" NUMBER(5,0) NOT NULL,
  "COMPANY_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "LOCATION" VARCHAR2(100 BYTE) NOT NULL,
  "REQUIREMENTS" VARCHAR2(300 BYTE) NOT NULL,
  "DESIGNATION" VARCHAR2(50 BYTE) NOT NULL,
  "SALARY" NUMBER(10,0)
)
TABLESPACE "DJANGO_DB_TBSP_PERM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of JOB_POST
-- ----------------------------
INSERT INTO "DJANGO_DB"."JOB_POST" VALUES ('12', 'company1', 'loca1', 'abcd', 'desig1', NULL);

-- ----------------------------
-- Primary Key structure for table JOB_POST
-- ----------------------------
ALTER TABLE "DJANGO_DB"."JOB_POST" ADD CONSTRAINT "JOB_PK" PRIMARY KEY ("POST_ID");

-- ----------------------------
-- Checks structure for table JOB_POST
-- ----------------------------
ALTER TABLE "DJANGO_DB"."JOB_POST" ADD CONSTRAINT "SYS_C0016079" CHECK ("POST_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DJANGO_DB"."JOB_POST" ADD CONSTRAINT "SYS_C0016080" CHECK ("COMPANY_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DJANGO_DB"."JOB_POST" ADD CONSTRAINT "SYS_C0016081" CHECK ("LOCATION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DJANGO_DB"."JOB_POST" ADD CONSTRAINT "SYS_C0016082" CHECK ("REQUIREMENTS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DJANGO_DB"."JOB_POST" ADD CONSTRAINT "SYS_C0016083" CHECK ("DESIGNATION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
