/*
 Navicat Premium Data Transfer

 Source Server         : PROJ
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Schema         : DJANGO_DB

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 18/11/2020 23:08:52
*/


-- ----------------------------
-- Table structure for USER_POSTS
-- ----------------------------
DROP TABLE "DJANGO_DB"."USER_POSTS";
CREATE TABLE "DJANGO_DB"."USER_POSTS" (
  "USER_ID" NUMBER(10,0) NOT NULL,
  "POST_ID" NUMBER(5,0) NOT NULL
)
TABLESPACE "DJANGO_DB_TBSP_PERM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of USER_POSTS
-- ----------------------------
INSERT INTO "DJANGO_DB"."USER_POSTS" VALUES ('1705015', '21');
INSERT INTO "DJANGO_DB"."USER_POSTS" VALUES ('1705015', '42');
INSERT INTO "DJANGO_DB"."USER_POSTS" VALUES ('1705015', '43');
INSERT INTO "DJANGO_DB"."USER_POSTS" VALUES ('1705015', '44');
INSERT INTO "DJANGO_DB"."USER_POSTS" VALUES ('1705015', '45');
INSERT INTO "DJANGO_DB"."USER_POSTS" VALUES ('1705015', '46');
INSERT INTO "DJANGO_DB"."USER_POSTS" VALUES ('1705015', '47');
INSERT INTO "DJANGO_DB"."USER_POSTS" VALUES ('1705015', '48');
INSERT INTO "DJANGO_DB"."USER_POSTS" VALUES ('1705015', '49');
INSERT INTO "DJANGO_DB"."USER_POSTS" VALUES ('1705015', '50');
INSERT INTO "DJANGO_DB"."USER_POSTS" VALUES ('1705015', '51');
INSERT INTO "DJANGO_DB"."USER_POSTS" VALUES ('1705015', '52');
INSERT INTO "DJANGO_DB"."USER_POSTS" VALUES ('1705018', '100');
INSERT INTO "DJANGO_DB"."USER_POSTS" VALUES ('1705015', '62');
INSERT INTO "DJANGO_DB"."USER_POSTS" VALUES ('1705015', '63');
INSERT INTO "DJANGO_DB"."USER_POSTS" VALUES ('1705015', '61');

-- ----------------------------
-- Primary Key structure for table USER_POSTS
-- ----------------------------
ALTER TABLE "DJANGO_DB"."USER_POSTS" ADD CONSTRAINT "USER_POSTS_PK" PRIMARY KEY ("POST_ID");

-- ----------------------------
-- Checks structure for table USER_POSTS
-- ----------------------------
ALTER TABLE "DJANGO_DB"."USER_POSTS" ADD CONSTRAINT "SYS_C0016139" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DJANGO_DB"."USER_POSTS" ADD CONSTRAINT "SYS_C0016140" CHECK ("POST_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
